language: julia

os:
    - linux

julia:
    - 0.6

notifications:
    email: false

after_success:
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("Lifting")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Lifting")); using Coverage; Codecov.submit(Codecov.process_folder())'
